name: Hello World Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "Hello World!"

      - name: Print current date
        run: date

      - name: List directory contents
        run: ls -l
